/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package finalproject;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.text.Position;

/**
 *
 * @author Edwin Chalumeau and Gloria Yam
 */
public class GUI extends javax.swing.JFrame {
    public String Stats;
    public String Pyear;
    public String Lname;
    public String Fname;
    String sfline ;
    String[] arr;
    String[] arr2;
    String[] arr3;
    Scanner s ;
     
   
    //FinalProject FP = new FinalProject(this.FP.Lname, this.FP.Fname, this.FP.Pyear, this.FP.Stats);
   
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Membership App");

        jLabel2.setText("Choose Family Name:");

        jButton1.setText("Read Family");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Member Information:");

        jLabel9.setText("Output");

        jButton2.setText("Sort");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Print File");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jList1);

        jButton4.setText(">");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jList2);

        jLabel3.setText("You can read: DDs, SAL, 610, HE, Rebelz, BL,Mafia, Phalcons");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(186, 186, 186)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel3)
                        .addGap(3, 3, 3)
                        .addComponent(jButton1)
                        .addGap(185, 185, 185)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(63, 63, 63)
                .addComponent(jButton3)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      
        try {
          // We are letting the user pick what family line that want to view.
            JFileChooser fc = new JFileChooser();
            // This will  tells us whether the user picked a file or not.
            int retval ; 
            
            File txtfile ;
            // open file chooser
            retval = fc.showOpenDialog(null) ;

          
            if (retval == JFileChooser.APPROVE_OPTION) {
                txtfile = fc.getSelectedFile() ;  // get file selected
            }    
            else {
                
                javax.swing.JOptionPane.showMessageDialog(null, "No file was selected program exited.");
                return ;
            }  
            
            FileReader fr = new FileReader(txtfile);

            BufferedReader bufr = new BufferedReader(fr);
           
            s = new Scanner(bufr);
          
            
            while( s.hasNext())  {
                {
             //scaning the names and stuff                  
            sfline = s.next();
            alist1.add(sfline) ;
                }
                  
            
             int i = 0 ;

    //create an array named arr that is sized the same as the arraylist
    //remember that arrays have to be sized ahead of time
    String[] arr = new String[alist1.size()];
    //arraylists have a toArray method that help us copy
    //their data into an array
    alist1.toArray(arr);

    //set the data source of the jlist box to the array
    jList1.setListData(arr);
          
        }  // copying the arraylist content to an array
  
            }catch (IOException e)   {
                 
            System.out.println(e.getMessage());
            
            javax.swing.JOptionPane.showMessageDialog(null, "Something messed Up");
        }
        
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
          // our first task is 
    // to store the item that
    // is highlited in the left jlist
    
    String svar ;


    int listindex = 0 ;
    // read the selected item in the jlist box
    svar = this.jList1.getSelectedValue().toString();
    String svar2 ;

    
    // lets search thru the arraylist
    // and find the element that matches the
    // highlighted row in the list box
    // record the index that points to it
    // in the listindex variable
    for (int i = 0; i < alist1.size(); i++ ){
        
        svar2 = alist1.get(i) ;
        // search the array
        if (svar.equals(svar2 )) {
            listindex = i;
        }
    }
    
    // now remove the element from the arrayList
    // recall that arraylists are a lot easire to work
    // with when you dynamically increase or decrease their size 
    alist1.remove(listindex);

    // copy arraylist to array so you can refresh the 
    // jlist
    
    // this time we use a for loop to copy 
    // the elements of the arraylist into an array
    // of equal size
    int i = 0 ;
    String[] arr = new String[alist1.size()];
    
    //check out this funcky "for loop"
    // it loops until you have navigated through
    // every element of the arraylist
    for (String elem : alist1) {
        arr[i] = elem ;
        i = i + 1 ;  // or i++
    }
    // arr now contains the data of the arraylist
    // set array as data source for listbox
    jList1.setListData(arr);
    
    // move item to alist2
    alist2.add(svar) ;
    
    
    
    // copy to array
    int j = 0 ;
    String[] arr2 = new String[alist2.size()];;
    alist2.toArray(arr2);
    
    
    // refresh the jlist
    jList2.setListData(arr2);
    
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //Sort 
         int j = 0 ;
    String[] arr2 = new String[alist2.size()];
    alist2.toArray(arr2);
    Arrays.sort(arr2);

      jList2.setListData(arr2);
        
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //Here is were we print the file to an html file. 
     String[] arr2 = new String[alist2.size()];
    alist2.toArray(arr2);
    Arrays.sort(arr2);
        try {
       File outtxtfile = new File("src/Outputfile/output.html") ;
       FileWriter fw = new FileWriter(outtxtfile) ;
            try (BufferedWriter rot = new BufferedWriter(fw)) {
              //this is the html code 
                rot.write("<html>") ;
                rot.write("");
                rot.newLine() ;
                rot.write("<body>");
                rot.newLine() ;
                rot.write("<h1>");
                rot.write("Inactive People");
                rot.write("</h1>");
                rot.newLine() ;
                rot.write("<ul>");
                // Here we want to move items from a Jlist into an array
                for (int h =0; h<arr2.length; h++)
                {
                    rot.newLine() ;
                    rot.write("<li>");
                    rot.write(arr2[h]);
                    rot.write("</li>");
                    
                }
                
                rot.newLine() ;
                rot.write("</ul>");
                rot.newLine() ;
                rot.write("</body>");
                rot.newLine() ;
                rot.write("</html>") ;
            }
        }catch (IOException e)   {
                 
            System.out.println(e.getMessage());
            
            javax.swing.JOptionPane.showMessageDialog(null, "Something messed Up");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
ArrayList<String> alist1 = new ArrayList<String>() ;

ArrayList<String> alist2 = new ArrayList<String>() ;



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
